# --- START OF FILE configs/config_full_500m.yaml ---
# Full configuration for a ~500M parameter model.
# Enables ALL components: BLT, Titans, T2, MVoT.
# Paths for BLT/MVoT components are null (random init).

# Core Model Parameters (~500M target)
hidden_size: 2048
num_layers: 24
num_attention_heads: 16
intermediate_size: 8192
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
max_position_embeddings: 4096 # Max number of patches or tokens
vocab_size: 260 # For BLT (byte vocab size)
layer_norm_eps: 1.0e-5

# Tokenizer (Not used when use_blt_processor is true)
tokenizer_name: null

# Component Activation Flags
use_blt_processor: true
use_titans_memory: true
use_transformer2_adaptation: true
use_mvot_processor: true

# Nested Component Configurations
blt:
  entropy_threshold: 0.5
  min_patch_size: 8
  max_patch_size: 128
  num_local_layers: 1
  num_latent_layers: 2
  byte_lm:
    hidden_size: 256
    num_layers: 4
    num_attention_heads: 4
    intermediate_size: 1024
    byte_lm_dropout: 0.1
    byte_lm_model_type: "transformer"
    byte_lm_max_position: 512 # Max context for the small LM
  blt_checkpoint_path: null # Path to pretrained SmallByteLM (if any)

titans:
  use_window_attention: true
  use_surprise_based: true
  use_persistent: true
  window_size: 512 # Window for short-term memory (num patches)
  num_persistent_vectors: 64
  persistent_init_scale: 0.02
  integration_layers: [0, 12, 23] # Default for 24 layers

  # MLP specific parameters
  memory_mlp_num_layers: 2
  mem_mlp_intermediate_size: 1024 # Relative to hidden_size=2048
  memory_learning_rate: 0.001    # Explicitly set lower than dataclass default
  memory_momentum: 0.9
  memory_weight_decay: 0.0001
  active_update_during_eval: true
  
  # Fields from old SurpriseMemory (less relevant for MLP, but kept for potential future use by MemoryComponent)
  memory_size: 4096
  surprise_threshold: 0.5
  base_decay_rate: 0.99
  importance_half_life: 1000
  memory_prune_threshold: 0.01
  surprise_method: "associative_loss_grad" # Consistent with MLP's internal update logic

transformer2:
  num_tasks: 8
  task_embedding_dim: 64
  num_singular_values: 128
  expert_init_scale: 0.01
  adapt_attention: true
  adapt_ffn: true
  adapt_embeddings: false # Typically not adapted for BLT
  adapt_lm_head: false    # MVoT projection is separate
  layer_specific: false
  use_randomized_svd: true
  svd_precision: "fixed"
  svd_n_oversamples: 10
  svd_n_iter: 5
  enable_svd_caching: true
  svd_cache_dir: ".svd_cache_full"

mvot:
  codebook_size: 8192
  embedding_dim: 2048 # Should match model's hidden_size
  discrepancy_loss_weight: 0.1
  codebook_model_type: "vqvae" # Hint for loading function
  codebook_path: null # Path to pretrained visual codebook
  use_pretrained_codebook: false # Set to false if path is null

# Data, Training, Hardware Configs
data:
  train_data_dir: "./src/data/processed_wikitext103/wikitext_wikitext-103-raw-v1_train" # Example path
  eval_data_dir: "./src/data/processed_wikitext103/wikitext_wikitext-103-raw-v1_eval"   # Example path
  train_file_pattern: "*.txt" 
  eval_file_pattern: "*.txt"
  block_size: 4096 # Sequence length in BYTES for BLT

training:
  learning_rate: 3.0e-4
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1.0e-8
  max_grad_norm: 1.0
  max_steps: 5000 # Reduced for initial test runs
  warmup_steps: 200  # Adjusted
  batch_size: 4      # Reduced
  gradient_accumulation_steps: 8 # Increased
  logging_steps: 50
  eval_steps: 500
  save_steps: 500
  output_dir: "./output/neat_full_500m_wikitext103" # Specific output dir
  resume_from: null

hardware:
  mixed_precision: true
  gradient_checkpointing: false # Good for initial stability
  force_cpu: false
  num_workers: 0 
  use_flash_attention: true
# --- END OF FILE configs/config_full_500m.yaml ---