# --- START OF FILE configs/config_base_500m.yaml ---
# Base configuration for a ~500M parameter model.
# Enables Titans Memory and Transformer2 Adaptation by default.
# Disables BLT and MVoT for simpler initial setup.
# Uses a standard Hugging Face tokenizer (e.g., gpt2).

# Core Model Parameters (~500M target)
hidden_size: 2048
num_layers: 24
num_attention_heads: 16
intermediate_size: 8192 # 4 * hidden_size
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
max_position_embeddings: 4096 # Should be >= data.block_size
vocab_size: 50257 # Default for GPT2, train.py will override based on tokenizer_name
layer_norm_eps: 1.0e-5 # Added for LayerNorm stability

# Tokenizer (Used when use_blt_processor is false)
tokenizer_name: "gpt2" # train.py will load this and update vocab_size

# Component Activation Flags
use_blt_processor: false
use_titans_memory: true
use_transformer2_adaptation: true
use_mvot_processor: false

# Nested Component Configurations
blt:
  entropy_threshold: 0.5
  min_patch_size: 8
  max_patch_size: 128
  num_local_layers: 1
  num_latent_layers: 2
  byte_lm:
    hidden_size: 256
    num_layers: 4
    num_attention_heads: 4
    intermediate_size: 1024
    byte_lm_dropout: 0.1
    byte_lm_model_type: "transformer"
    byte_lm_max_position: 512
  blt_checkpoint_path: null

titans:
  use_window_attention: true
  use_surprise_based: true
  use_persistent: true
  window_size: 512
  memory_size: 4096
  surprise_threshold: 0.5
  num_persistent_vectors: 64
  persistent_init_scale: 0.02
  base_decay_rate: 0.99
  importance_half_life: 1000
  memory_prune_threshold: 0.01
  surprise_method: "gradient_norm"

transformer2:
  num_tasks: 8
  task_embedding_dim: 64
  num_singular_values: 128 # k
  expert_init_scale: 0.01
  adapt_attention: true
  adapt_ffn: true
  adapt_embeddings: false
  adapt_lm_head: false
  layer_specific: false
  use_randomized_svd: true
  svd_precision: "fixed"
  svd_n_oversamples: 10
  svd_n_iter: 5
  enable_svd_caching: true
  svd_cache_dir: ".svd_cache_base"

mvot:
  codebook_size: 8192
  embedding_dim: 2048 # Matches hidden_size
  discrepancy_loss_weight: 0.1
  codebook_model_type: "vqvae"
  codebook_path: null
  use_pretrained_codebook: false # Set to false if path is null

# Data, Training, Hardware Configs
data:
  train_data_dir: "./src/data/processed_wikitext103/wikitext_wikitext-103-raw-v1_train"
  eval_data_dir: "./src/data/processed_wikitext103/wikitext_wikitext-103-raw-v1_eval"
  train_file_pattern: "*.txt" # Matches output from prepare_data.py
  eval_file_pattern: "*.txt"
  block_size: 1024 # Max sequence length in tokens for wikitext-103

training:
  learning_rate: 3.0e-4
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1.0e-8
  max_grad_norm: 1.0
  max_steps: 5000 # Reduced for initial test runs, was 200000
  warmup_steps: 200  # Adjusted relative to max_steps, was 2000
  batch_size: 4      # Reduced for potentially smaller GPUs, was 8
  gradient_accumulation_steps: 8 # Increased to maintain effective batch size, was 4
  logging_steps: 50
  eval_steps: 500
  save_steps: 500
  output_dir: ".src/output/neat_base_500m_wikitext103" # Specific output dir
  resume_from: null

hardware:
  mixed_precision: true
  gradient_checkpointing: false # Keep false for initial debugging
  force_cpu: false
  num_workers: 0 # Set to 0 for easier debugging on Windows, was 4
  use_flash_attention: true
# --- END OF FILE configs/config_base_500m.yaml ---